name: CI/CD

on:
  push:
    branches: ["master"]
  workflow_dispatch:

jobs:
  build:
    steps:
      - name: Deploy with SSH and rsync
        uses: burnett01/rsync-deployments@7.0.1
        with:
          switches: -vr
          path: /
          remote_path: /var/www/ericolsen.us/resume
          remote_host: ${{ secrets.HOMESERVER_URL }}
          remote_user: ${{ secrets.HOMESERVER_DEPLOY_USER }}
          remote_key: ${{ secrets.HOMESERVER_DEPLOY_KEY }}
          remote_key_pass: ${{ secrets.HOMESERVER_DEPLOY_PASS }}
