name: CI/CD

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Serve Files
        uses: Eun/http-server-action@v1
        with:
          directory: ${{ github.workspace }}
          port: 8080
          no-cache: true
          index-files: |
            ["index.html", "index.htm"]
          allowed-methods: |
            ["GET", "HEAD"]
          content-types: |
            {
              ".html": "text/html",
              ".css": "text/css"
            }

      - name: Test HTTP Server
        run: |
          curl http://localhost:8080

      - name: HTML to PDF
        uses: misaelnieto/web_to_pdf_action@v0.3.1
        with:
          webPageURL: http://localhost:8080
          outputFile: ${{ github.workspace }}/Eric-F-Olsen-Resume.pdf

      - name: Deploy with SSH and rsync
        uses: burnett01/rsync-deployments@7.0.1
        with:
          switches: -vr --delete-after --exclude .git/ --exclude .github/ --exclude .gitmodules --exclude LICENSE --exclude README.md
          remote_path: /var/www/ericolsen.us/resume
          remote_host: ${{ secrets.HOMESERVER_URL }}
          remote_user: ${{ secrets.HOMESERVER_DEPLOY_USER }}
          remote_key: ${{ secrets.HOMESERVER_DEPLOY_KEY }}
          remote_key_pass: ${{ secrets.HOMESERVER_DEPLOY_PASS }}
